[package]
name = "anidb-api"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Dmitriy <ataraxiadev@ataraxiadev.com>"]
description = "Rust library that provides wrapper for AniDB API"
homepage = "https://github.com/AtaraxiaSjel/anidb-api-rs"
readme = "README.md"

[dependencies]
