[package]
name = "anidb-api"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Dmitriy <ataraxiadev@ataraxiadev.com>"]
description = "Rust library that provides wrapper for AniDB API"
repository = "https://github.com/AtaraxiaSjel/anidb-api-rs"
readme = "README.md"
exclude = [
  ".cargo",
  ".envrc",
  "deny.toml",
  "flake.nix",
  "flake.lock",
  "taplo.toml",
]

[dependencies]
aes = { version = "0.8.4", optional = true }
ascii = { version = "1.1.0", optional = true }
async-trait = "0.1.88"
ecb = { version = "0.1.2", features = ["alloc"], optional = true }
ecow = { version = "0.2.5", optional = true }
flate2 = { version = "1.1.1", optional = true }
format-bytes = { version = "0.3.0", optional = true }
governor = "0.10.0"
http = { version = "1.3.1", optional = true }
http-serde = { version = "2.1.1", optional = true }
itertools = { version = "0.14.0", optional = true }
md-5 = { version = "0.10.6", optional = true }
nonzero = { version = "0.2.0", optional = true }
random-port = { version = "0.1.1", optional = true }
reqwest = { version = "0.12.15", features = ["gzip"], optional = true }
reqwest-middleware = { version = "0.4.2", optional = true }
reqwest-ratelimit = { version = "0.4.1", optional = true }
reqwest-tracing = { version = "0.5.7", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = { version = "0.7.1", optional = true }
thiserror = "2.0.12"
tokio = { version = "1", features = ["net", "rt", "time"], optional = true }
tracing = { version = "0.1.41", features = ["log"] }
udp-stream = { version = "0.0.12", optional = true }
url = { version = "2.5.4", optional = true }

[dev-dependencies]
dotenvy = "0.15.7"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = ["http", "udp"]
http = [
  "dep:http",
  "dep:http-serde",
  "dep:reqwest",
  "dep:reqwest-middleware",
  "dep:reqwest-ratelimit",
  "dep:reqwest-tracing",
  "dep:serde-xml-rs",
  "dep:url",
]
udp = [
  "dep:aes",
  "dep:ascii",
  "dep:ecb",
  "dep:ecow",
  "dep:flate2",
  "dep:format-bytes",
  "dep:itertools",
  "dep:md-5",
  "dep:nonzero",
  "dep:random-port",
  "dep:tokio",
  "dep:udp-stream",
]

[lints.rust]
unsafe_code = "forbid"
warnings = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
